from config import *
import time

def plant_seed():
    set_angle(BASE, 45)
    time.sleep(0.5)
    set_angle(SHOULDER, 60)
    time.sleep(0.5)
    set_angle(ELBOW, 90)
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 30)
    time.sleep(0.5)
    rotate_servo(GRIPPER, "clockwise")
    time.sleep(1)
    rotate_servo(GRIPPER, "stop")
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 0)
    set_angle(ELBOW, 0)
    set_angle(SHOULDER, 0)
    set_angle(BASE, 0)

def remove_weed():
    set_angle(BASE, 90)
    time.sleep(0.5)
    set_angle(SHOULDER, 45)
    time.sleep(0.5)
    set_angle(ELBOW, 120)
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 60)
    time.sleep(0.5)
    rotate_servo(GRIPPER, "counterclockwise")
    time.sleep(1.5)
    rotate_servo(GRIPPER, "stop")
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 0)
    set_angle(ELBOW, 0)
    set_angle(SHOULDER, 0)
    set_angle(BASE, 0)

def harvest_crop():
    set_angle(BASE, 135)
    time.sleep(0.5)
    set_angle(SHOULDER, 30)
    time.sleep(0.5)
    set_angle(ELBOW, 60)
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 45)
    time.sleep(0.5)
    rotate_servo(WRIST_ROTATE, "clockwise")
    time.sleep(2)
    rotate_servo(WRIST_ROTATE, "stop")
    time.sleep(0.5)
    rotate_servo(GRIPPER, "clockwise")
    time.sleep(1)
    rotate_servo(GRIPPER, "stop")
    time.sleep(0.5)
    set_angle(WRIST_PITCH, 0)
    set_angle(ELBOW, 0)
    set_angle(SHOULDER, 0)
    set_angle(BASE, 0)
